require("pipeR")


require("data.table")
require('filehash')

require('ggplot2')
require('gridExtra')
require('wordcloud')


cache.fn <- "cache/dbCache"
cachePre.fn <- "cache/dbCachePre"
if (!file.exists('cache')) dir.create('cache')
if (!file.exists(cache.fn)) dbCreate(cache.fn)
if (!file.exists(cachePre.fn)) dbCreate(cachePre.fn)
dbCache <- dbInit(cache.fn)
dbCachePre <- dbInit(cachePre.fn)


downloadCourseraSwiftKey <- function() {
  if (!file.exists('data')) dir.create('data')
  zip.url <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
  zip.fn <- "data/Coursera-SwiftKey.zip"
  if (!file.exists(zip.fn)) download.file(zip.url, destfile=zip.fn, method="curl")
  if (!file.exists('data/final')) unzip(zip.fn, exdir='data')
}

read.datafile <- function(fn, n=-1L) {
  txts <- readLines(fn, n)
  data.table(words=txts)
}


treatPunctuation <- function(txts) {
  ## we split, but we can also remove only
  unlist(strsplit(txts, "(?!@|'|-|#)[[:punct:]]| -+ ", perl=TRUE))  
}

trim <- function (txts) gsub("^\\s+|\\s+$", "", txts)

removeExtraSpace <- function(txts) {
  gsub("\\s\\s+", " ", txts)
}

txts.clean <- function(txts) {
  txts %>>%
    tolower %>>%
    treatPunctuation %>>%
    removeExtraSpace %>>%
    trim
}

txt.tokens <- function(txt) unlist(strsplit(txt, ' '))

txts.tokens <- function(txts) {
  txts %>>%
    txt.tokens
}

cleanDT <- function(dt) {
  dt[,.(words=txts.clean(words))][words!=""][,id:=.I]
}

tokenizeDT <- function(dt) {
  dt[,.(tokens1=txts.tokens(words)), by=id]
}

basicDT <- function(dt) {
  ## dt: data.table with column words: characters
  dt %>>%
    cleanDT %>>%
    tokenizeDT
}

getTokens <- function(vn, fn, n=-1L) {
  if (dbExists(dbCache, vn)) {
    v <- dbFetch(dbCache, vn)
  } else {
    v <- read.datafile(fn, n) %>>%
      basicDT()
    dbInsert(dbCache, vn, v)
  }
  v
}

### N grams

ngramDTs <- function(dt, n) {
  N <- dim(dt)[1]
  ngrams.dts <- list()
  ngrams.dts[[1]] <- dt
  if (n>=2) {
    for (k in 2:n) {
      ngrams.dts[[k]] <-  cbind(ngrams.dts[[k-1]][1:(N-k+1),!"newid", with=FALSE] , dt[k:N])
      setnames(ngrams.dts[[k]], c(colnames(ngrams.dts[[k-1]][,!"newid", with=FALSE]),
               "newid", paste0("tokens", k)))
    }
  }
  if (n>=2) {
    for (k in 2:n) {
      ngrams.dts[[k]] <- ngrams.dts[[k]][id==newid][,!"newid", with=FALSE]
    }
  }
  ngrams.dts
}

dbFetchOrInsert <- function(db, name, f) {
  if (dbExists(db, name)) {
    return(dbFetch(db, name))
  } else {
    v <- f()
    dbInsert(db, name, v)
    return(v)
  }
}

newKGramsTable <- function(dt.acc, dt1, N, k, echo=FALSE) {
  
  ## k: kgrams to create
  ## dt.accc: k-1 grams
  ## dt1: table of tokens (generated by basicDT)
  ## N: row numbers of dt1
  
  if (k==2) {
    cnames.old <- colnames(dt.acc)
    dt.new <-  cbind(dt.acc[1:(N-1)] , dt1[2:N])
  } else {
    cnames.old <- colnames(dt.acc[,!"newid", with=FALSE])
    dt.new <-  cbind(dt.acc[1:(N-k+1),!"newid", with=FALSE] , dt1[k:N])
  }
  setnames(dt.new,
           c(cnames.old, "newid", paste0("tokens", k)))
  if (echo) print(object.size(dt.new))
  dt.new
}


preNGrams.name <- function(name, k) {
  paste0(name, "Pre", k, "grams")
}

dbDeletePattern <- function(db, pattern, echo=FALSE) {
  vs <- dbList(db)
  vs <- vs[grep(pattern, vs)]
  if (echo) {
    print("removing from db:")
    print(vs)
  }
  for (v in vs) dbDelete(db, v)
}

dbDeletePreRecords <- function(name, echo=FALSE) {
  pattern <- paste0("^",name,"Pre[0-9]+grams$")
  dbDeletePattern(dbCachePre, pattern, echo)
}

preNGramsFH <- function(name, n, dt=NULL, overwrite=FALSE, echo=FALSE) {
  if (overwrite) {
    dbDeletePreRecords(name, echo)
  }
  if (echo) print(paste('creating', preNGrams.name(name, 1)))
  dt1 <- dbFetchOrInsert(dbCachePre, preNGrams.name(name, 1),
                         function() dt)
  N <- dim(dt1)[1]
  dt.acc <- dt1
  if (n>=2) {
    for (k in 2:n) {
      if (echo) print(paste('creating', preNGrams.name(name, k)))
      if (k>N) return()
      dt.acc <- dbFetchOrInsert(dbCachePre, preNGrams.name(name, k),
                                function() newKGramsTable(dt.acc, dt1, N, k, echo))
    }
  }
  dt.acc
}


nGrams.name <- function(name, k) {
  paste0(name, k, "grams")
}

dbDeleteRecords <- function(name, echo=FALSE) {
  pattern <- paste0("^",name,"[0-9]+grams$")
  dbDeletePattern(dbCache, pattern, echo) 
}

ktokens <- function(k) sapply(1:k, function(x) paste0("tokens",x))

nGramsFH <- function(name, n, dt=NULL, overwrite=FALSE, echo=FALSE) {
  if (overwrite) {
    dbDeleteRecords(name, echo)
  }
  if (dbExists(dbCache, nGrams.name(name, n))) {
    if (echo) print(paste("getting", n, "-grams from cache" ))
    return(dbFetch(dbCache, nGrams.name(name, n)))
  }
  preNGramsFH(name, n, dt, overwrite, echo)
  if (echo) print("1-grams")
  dt.counts <- dbFetchOrInsert(
    dbCache, nGrams.name(name, 1),
    function() dbFetch(dbCachePre, preNGrams.name(name, 1))[,.(counts=.N),by=tokens1])
  if (n>=2) {
    for (k in 2:n) {
      if (echo) print(paste0(k,"-grams"))
      tokens.k <- ktokens(k)
      dt.counts <- dbFetchOrInsert(
        dbCache,
        nGrams.name(name, k),
        function() {
          predt <- dbFetch(dbCachePre, preNGrams.name(name, k))
          predt[id==newid, .(counts=.N), by=tokens.k]
        })
    }
  }
  dt.counts
}

createEmptyTotalDT <- function(k) {
  et.dt <- data.table(matrix(1:(k+1), nrow=1))
  setnames(et.dt, c(ktokens(k),'counts'))
  et.dt[0]
}

createEmptyTotalFH <- function(name, n) {
  for (k in 1:n) {
    dbInsert(dbCache, nGramsTotal.name(name, k), createEmptyTotalDT(k))
  }
}

nGramsTotal.name <- function(name, k) {
  paste0(name, "Total", k, "grams")
}

nGramsPart.name <- function(name, k, j) {
  paste0(name, j, "h", k, "grams")
}

dbDeletePartRecords <- function(name, echo=FALSE) {
  pattern <- paste0("^", name, "[0-9]+h[0-9]+grams$")
  dbDeletePattern(dbCache, pattern, echo)
  pattern <- paste0("^", name, "[0-9]+hPre[0-9]+grams$")
  dbDeletePattern(dbCachePre, pattern, echo) 

}

dbDeleteTotalRecords <- function(name, echo=FALSE) {
  pattern <- paste0("^", name, "Total[0-9]+grams$")
  dbDeletePattern(dbCache, pattern, echo) 
}

addNGramsFH <- function(name, nameTotal, n, dt, K=3, echo=FALSE) {
  if (!dbExists(dbCache, nGramsTotal.name(nameTotal, 1))) {
      createEmptyTotalFH(nameTotal, n)
  }
  idj <- 0
  Ntot <- dim(dt)[1]
  for (j in 1:(K-1)) {
    idj[j+1] <- dt[floor(j*Ntot/K), id]
  }
  idj[K+1] <- dt[Ntot, id]
  for (j in 1:K) {
    if (echo) paste('Part', j)
    nGramsFH(paste0(name, j, 'h'), n, dt[id>idj[j] & id<=idj[j+1]], TRUE, echo)
    for (k in 1:n) {
      tokens.k <- ktokens(k)
      dt.total <- dbFetch(dbCache, nGramsTotal.name(nameTotal, k))
      dt.part <- dbFetch(dbCache, nGramsPart.name(name, k, j ))
      dt.total <- rbind(dt.total, dt.part)[,.(counts=sum(counts)),by=tokens.k]
      dbInsert(dbCache, nGramsTotal.name(nameTotal, k), dt.total)
    }
  }
  dbDeletePartRecords(name, echo)
}
