require("pipeR")


require("data.table")
require('filehash')

require('ggplot2')
require('gridExtra')
require('wordcloud')


cache.fn <- "cache/dbCache"
if (!file.exists('cache')) dir.create('cache')
if (!file.exists(cache.fn)) dbCreate(cache.fn)
dbCache <- dbInit(cache.fn)


downloadCourseraSwiftKey <- function() {
  if (!file.exists('data')) dir.create('data')
  zip.url <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
  zip.fn <- "data/Coursera-SwiftKey.zip"
  if (!file.exists(zip.fn)) download.file(zip.url, destfile=zip.fn, method="curl")
  if (!file.exists('data/final')) unzip(zip.fn, exdir='data')
}

read.datafile <- function(fn, n=-1L) {
  txts <- readLines(fn, n)
  data.table(words=txts)
}


treatPunctuation <- function(txts) {
  ## we split, but we can also remove only
  unlist(strsplit(txts, "(?!@|'|-|#)[[:punct:]]| -+ ", perl=TRUE))  
}

trim <- function (txts) gsub("^\\s+|\\s+$", "", txts)

removeExtraSpace <- function(txts) {
  gsub("\\s\\s+", " ", txts)
}

txts.clean <- function(txts) {
  txts %>>%
    tolower %>>%
    treatPunctuation %>>%
    removeExtraSpace %>>%
    trim
}

txt.tokens <- function(txt) unlist(strsplit(txt, ' '))

txts.tokens <- function(txts) {
  txts %>>%
    txt.tokens
}

cleanDT <- function(dt) {
  dt[,.(words=txts.clean(words))][words!=""][,id:=.I]
}

tokenizeDT <- function(dt) {
  dt[,.(tokens1=txts.tokens(words)), by=id]
}

basicDT <- function(dt) {
  ## dt: data.table with column words: characters
  dt %>>%
    cleanDT %>>%
    tokenizeDT
}

getTokens <- function(vn, fn, n=-1L) {
  if (dbExists(dbCache, vn)) {
    v <- dbFetch(dbCache, vn)
  } else {
    v <- read.datafile(fn, n) %>>%
      basicDT()
    dbInsert(dbCache, vn, v)
  }
  v
}

### N grams

ngramDTs <- function(dt, n) {
  N <- dim(dt)[1]
  ngrams.dts <- list()
  ngrams.dts[[1]] <- dt
  if (n>=2) {
    for (k in 2:n) {
      ngrams.dts[[k]] <-  cbind(ngrams.dts[[k-1]][1:(N-k+1),!"newid", with=FALSE] , dt[k:N])
      setnames(ngrams.dts[[k]], c(colnames(ngrams.dts[[k-1]][,!"newid", with=FALSE]),
               "newid", paste0("tokens", k)))
    }
  }
  if (n>=2) {
    for (k in 2:n) {
      ngrams.dts[[k]] <- ngrams.dts[[k]][id==newid][,!"newid", with=FALSE]
    }
  }
  ngrams.dts
}

dbFetchOrInsert <- function(db, name, f) {
  if (dbExists(db, name)) {
    return(dbFetch(dbCache, name))
  } else {
    v <- f()
    dbInsert(db, name, v)
    return(v)
  }
}

newKGramsTable <- function(dt.acc, dt1, N, k) {
  
  ## k: kgrams to create
  ## dt.accc: k-1 grams
  ## dt1: table of tokens (generated by basicDT)
  ## N: row numbers of dt1
  
  if (k==2) {
    cnames.old <- colnames(dt.acc)
    dt.new <-  cbind(dt.acc[1:(N-1)] , dt1[2:N])
  } else {
    cnames.old <- colnames(dt.acc[,!"newid", with=FALSE])
    dt.new <-  cbind(dt.acc[1:(N-k+1),!"newid", with=FALSE] , dt1[k:N])
  }
  setnames(dt.new,
           c(cnames.old, "newid", paste0("tokens", k)))
  dt.new
}


preNGrams.name <- function(name, k) {
  paste0(name, "Pre", k, "grams")
}

preNGramsFH <- function(name, n, dt=NULL, overwrite=FALSE) {
  if (overwrite) {
    vs <- dbList(dbCache)
    vs <- vs[grep("^alaPre[0-9]+grams$", vs)]
    for (v in vs) dbDelete(dbCache, v)
  }
  dt1 <- dbFetchOrInsert(dbCache, preNGrams.name(name, 1),
                         function() dt)
  N <- dim(dt1)[1]
  dt.acc <- dt1
  if (n>=2) {
    for (k in 2:n) {
      if (k>N) return()
      dt.acc <- dbFetchOrInsert(dbCache, preNGrams.name(name, k),
                                function() newKGramsTable(dt.acc, dt1, N, k))
    }
  }
  dt.acc
}


nGrams.name <- function(name, k) {
  paste0(name, k, "grams")
}

nGramsFH <- function(name, n, dt=NULL, overwrite=FALSE) {
  preNGramsFH(name, n, dt, overwrite)
  if (overwrite) {
    vs <- dbList(dbCache)
    vs <- vs[grep("^ala[0-9]+grams$", vs)]
    for (v in vs) dbDelete(dbCache, v)
  }
  if (dbExists(dbCache, nGrams.name(name, n))) {
    return(dbFetch(dbCache, nGrams.name(name, n)))
  }
  dt.counts <- dbFetchOrInsert(
    dbCache, nGrams.name(name, 1),
    function() dbFetch(dbCache, preNGrams.name(name, 1))[,.(counts=.N),by=tokens1])
  if (n>=2) {
    for (k in 2:n) {
      ktokens <- sapply(1:k, function(x) paste0("tokens",x))
      dt.counts <- dbFetchOrInsert(
        dbCache,
        nGrams.name(name, k),
        function() dbFetch(dbCache,
                           preNGrams.name(name, k))[id==newid,
                                                    .(counts=.N),
                                                    by=ktokens])
    }
  }
  dt.counts
}
